import {useCallback,useEffect,useState} from 'react';
import type {Bundle,Forecast} from './contracts.generated';
import {loadBundle,freshness,pkTime,probability,safeURL,type Loaded} from './data';

type Page='Overview'|'Watchlist'|'Evidence'|'Drivers'|'Health';
const pages:Page[]=['Overview','Watchlist','Evidence','Drivers','Health'];
const glyphs=['\u25c9','\u2261','\u25a5','\u2197','\u25c7'];
type Score={stage:string;horizon:number;scope:string;accuracy:number|null;coverage:number|null;count:number;unique_dates:number;start:string;end:string;selected_correctness:number|null;uncertainty:{low:number|null;high:number|null};brier:number|null;baseline_brier?:number;calibration:{count:number;mean_probability:number|null;observed_up:number|null}[]};
function Empty({title,children}:{title:string;children:React.ReactNode}){return <div className="empty"><span className="empty-mark" aria-hidden="true">↗</span><h3>{title}</h3><p>{children}</p></div>;}
function PageTitle({kicker,title,detail}:{kicker:string;title:string;detail:string}){return <div className="page-title"><p className="eyebrow">{kicker}</p><h1>{title}</h1><p>{detail}</p></div>;}
function Horizon({value,set}:{value:number;set:(v:number)=>void}){return <div className="segmented" role="group" aria-label="Forecast horizon">{[1,5].map(h=><button key={h} aria-pressed={h===value} onClick={()=>set(h)}>{h} session{h===5?'s':''}</button>)}</div>;}
function ScoreValue({label,value,detail}:{label:string;value:string;detail?:string}){return <div className="score"><span>{label}</span><strong className="numeric">{value}</strong>{detail&&<small>{detail}</small>}</div>;}

function Overview({bundle,horizon,setHorizon,now}:{bundle:Bundle|null;horizon:number;setHorizon:(v:number)=>void;now:number}){
 const f=bundle?.forecasts.find(f=>f.instrument==='PSX:KSE100:TR'&&f.horizon===horizon);
 const state=bundle?freshness(bundle,f,now):{state:'unavailable',label:'Waiting for published results',reason:'Checking the last published research bundle.'};
 const signal=state.state!=='current'?state.label:f?.signal==='up'?'Upward signal':f?.signal==='not_up'?'Downward or unchanged signal':'No strong signal';
 return <>
 <div className="overview-heading"><PageTitle kicker="Pakistan · Index research" title="KSE-100 market outlook" detail="Official total-return index · A probability, with its evidence."/><Horizon value={horizon} set={setHorizon}/></div>
 <div className="outlook-grid"><section className="forecast-panel" aria-labelledby="forecast-title">
  <div className="panel-top"><h2 id="forecast-title">The next {horizon===1?'session':'5 sessions'}</h2><span className="label">TOTAL RETURN</span></div>
  <div className="probability-pair"><div><p>Up</p><strong className="numeric">{probability(f?.p_up)}</strong><small>{f?.p_up==null?'No estimate available':'Estimated probability'}</small></div><div><p>Down or unchanged</p><strong className="numeric">{probability(f?.p_not_up)}</strong><small>{f?.p_not_up==null?'No estimate available':'Includes an unchanged close'}</small></div></div>
  {f?.p_up!=null&&<div className="probability-bar" role="img" aria-label={`Up ${probability(f.p_up)}; down or unchanged ${probability(f.p_not_up)}`}><span style={{width:`${f.p_up*100}%`}}/></div>}
  <div className={'signal '+(state.state==='current'?'signal-current':'')}><span className="status-dot" aria-hidden="true"/><div><strong>{signal}</strong><p>{state.reason}</p>{f?.validation_status==='research'&&<p>Estimated probability; validation pending.</p>}</div></div>
  <dl className="forecast-dates"><div><dt>Reference session</dt><dd>{f?.reference_session||'Not available'}</dd></div><div><dt>Target session</dt><dd>{f?.target_session||'Awaiting exchange calendar'}</dd></div></dl>
 </section><aside className="research-note"><p className="eyebrow">The research standard</p><h2>Confidence must<br/>be earned.</h2><p>Every estimate needs timely data, a clear target and an honest test against the past.</p><div className="note-rule"/><p className="note-small">No demonstrated forecasting advantage yet.</p><p className="note-small">Company forecasts are evaluated separately from the index.</p><span className="note-signature">KSE / Research desk</span></aside></div>
 <section className="timing-strip" aria-label="Update information"><div><span>Last successful prediction</span><strong>{pkTime(bundle?.stages.prediction)}</strong></div><div><span>Next expected update</span><strong>{pkTime(bundle?.update_due_at)}</strong></div><div><span>Display timezone</span><strong>Pakistan · Asia/Karachi</strong></div></section>
 <section className="reading-guide"><div><span className="guide-number">01</span><h3>Probability</h3><p>An estimate for one defined future event. It is not a measured success rate.</p></div><div><span className="guide-number">02</span><h3>Historical correctness</h3><p>How often past predictions were correct, over stated dates and with uncertainty.</p></div><div><span className="guide-number">03</span><h3>Coverage</h3><p>How often a directional signal was issued. "No strong signal" is an abstention.</p></div></section>
 </>;
}
function Watchlist({bundle,horizon,now}:{bundle:Bundle|null;horizon:number;now:number}){
 const [query,setQuery]=useState('');const [sort,setSort]=useState('symbol');const [sector,setSector]=useState('all');
 const rows=(bundle?.forecasts||[]).filter(f=>!f.instrument.includes('KSE100')&&f.horizon===horizon&&(f.instrument+' '+(f.instrument_name||'')+' '+(f.symbol||'')).toLowerCase().includes(query.toLowerCase())&&(sector==='all'||f.sector===sector)).sort((a,b)=>sort==='symbol'?a.instrument.localeCompare(b.instrument):b.issued_at.localeCompare(a.issued_at));
 return <><PageTitle kicker="Company research" title="A watchlist with its own evidence" detail="A company never inherits the index's probabilities or scorecard."/><div className="filters"><label>Find a company<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Company or symbol"/></label><label>Sector<select value={sector} onChange={e=>setSector(e.target.value)}><option value="all">All sectors</option>{[...new Set((bundle?.forecasts||[]).map(f=>f.sector).filter(Boolean))].map(name=><option key={name} value={name!}>{name}</option>)}</select></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="symbol">Symbol</option><option value="updated">Last issuance</option></select></label></div>{rows.length?<div className="table-wrap"><table><thead><tr><th>Company / symbol</th><th>Up</th><th>Research status</th><th>Input freshness</th></tr></thead><tbody>{rows.map(f=><tr key={f.instrument}><th>{f.instrument_name||f.instrument}<small>{f.symbol} · {f.sector||"Sector unavailable"}</small></th><td>{probability(f.p_up)}</td><td>{f.validation_status}</td><td>{freshness(bundle!,f,now).label}</td></tr>)}</tbody></table></div>:<Empty title="Company coverage is not ready">Dated constituent membership, liquidity and corporate actions must be verified before a 10-20 company watchlist can be selected.</Empty>}</>;
}
function Calibration({bins}:{bins:Score['calibration']}){
 const available=bins.filter(b=>b.count>0&&b.mean_probability!==null&&b.observed_up!==null);
 return <div className="calibration"><svg viewBox="0 0 320 260" role="img" aria-label="Calibration: predicted up probability compared with the observed up frequency. Bin counts are listed below."><line x1="40" y1="220" x2="280" y2="20" className="ideal"/><line x1="40" y1="20" x2="40" y2="220"/><line x1="40" y1="220" x2="280" y2="220"/><text x="10" y="24">1</text><text x="18" y="225">0</text><text x="275" y="240">1</text><text x="95" y="258">Predicted probability</text>{available.map((b,i)=><circle key={i} cx={40+b.mean_probability!*240} cy={220-b.observed_up!*200} r="5"><title>{b.count} outcomes; predicted {probability(b.mean_probability)}, observed {probability(b.observed_up)}</title></circle>)}</svg><p>Observed up frequency on the vertical axis. The dashed line represents perfect calibration.</p><ul>{available.map((b,i)=><li key={i}>{probability(b.mean_probability)} estimated → {probability(b.observed_up)} observed · {b.count} outcomes</li>)}</ul></div>;
}
function Evidence({bundle,horizon}:{bundle:Bundle|null;horizon:number}){
 const [stage,setStage]=useState('historical');
 const scores=(bundle?.metrics||[]).filter(m=>m.stage===stage&&m.horizon===horizon) as unknown as Score[];
 const selected=scores[0];
 const history=(bundle?.history||[]).filter(f=>f.horizon===horizon);
 return <><PageTitle kicker="Results, with support" title="Evidence before conviction" detail="Historical research, an untouched final test and forward observation are different forms of evidence."/><div className="segmented evidence-tabs" role="group" aria-label="Evidence period">{[['historical','Historical'],['final_test','Final test'],['forward','Forward']].map(([key,label])=><button key={key} aria-pressed={stage===key} onClick={()=>setStage(key)}>{label}</button>)}</div>{!selected?<Empty title="No measured market results yet">A permitted historical dataset and completed chronological evaluation are required. No accuracy, calibration or coverage percentage is being claimed.</Empty>:<><div className="scores"><ScoreValue label="Correctness" value={probability(selected.accuracy)}/><ScoreValue label="Signal coverage" value={probability(selected.coverage)}/><ScoreValue label="Matured outcomes" value={String(selected.count)} detail={`${selected.unique_dates} distinct dates`}/><ScoreValue label="Selected correctness" value={probability(selected.selected_correctness)} detail={`95% interval ${probability(selected.uncertainty.low)} to ${probability(selected.uncertainty.high)}`}/></div><p>{selected.start} to {selected.end} · {selected.scope} · {horizon} session horizon</p><h2>Probability calibration</h2><Calibration bins={selected.calibration}/><p>Brier score: {selected.brier?.toFixed(4)??'Not available'} · Historical-frequency baseline: {selected.baseline_brier?.toFixed(4)??'Not available'}. Lower is better.</p></>}
 <section className="history"><h2>Signal history</h2><p>Failures, abstentions and corrections belong in the record.</p>{history.length?<div className="table-wrap"><table><thead><tr><th>Reference</th><th>Instrument</th><th>Up</th><th>Decision</th><th>Outcome / correction</th></tr></thead><tbody>{history.map(f=>{const key=`${f.instrument}|${f.reference_session}|${f.horizon}|${f.policy}`;const outcomes=bundle!.outcomes.filter(o=>o.forecast_key===key);return <tr key={key}><td>{f.reference_session}</td><td>{f.instrument}</td><td>{probability(f.p_up)}</td><td>{f.signal.replaceAll('_',' ')}{f.suppression_reason&&<small>{f.suppression_reason}</small>}</td><td>{outcomes.length?outcomes.map(o=>o.direction+(o.correction_of?' (corrected)':'')).join('; '):'Awaiting validated outcome'}</td></tr>;})}</tbody></table></div>:<p className="quiet-box">No prospective forecasts have been issued.</p>}</section></>;
}
function Drivers({bundle}:{bundle:Bundle|null}){
 return <><PageTitle kicker="Information available at the cutoff" title="What the model can know" detail="Observed changes can contribute to an estimate. They do not prove what caused a future move."/>{bundle?.drivers.length?<div className="driver-list">{bundle.drivers.map((d,i)=><article key={i}><h2>{String(d.name)}</h2><p>{String(d.change)}</p><p>{pkTime(String(d.available_at))}</p><a href={safeURL(d.source_url)} rel="noreferrer" target="_blank">Official source ↗</a></article>)}</div>:<Empty title="Driver observations are not yet available">Oil, currency, rates and investor flows will appear with publication times and source links after their data checks pass.</Empty>}<div className="reading-guide"><div><span className="guide-number">A</span><h3>Market & macro</h3><p>Price history first. Oil, exchange rates, rates and flows are added one group at a time.</p></div><div><span className="guide-number">B</span><h3>Published events</h3><p>Inflation, policy and company releases enter only after their actual publication.</p></div><div><span className="guide-number">C</span><h3>Keep what helps</h3><p>Each driver needs a chronological comparison on the same dates and targets.</p></div></div></>;
}
function Health({bundle,offline,error}:{bundle:Bundle|null;offline:boolean;error:string|null}){
 return <><PageTitle kicker="Operational transparency" title="The state of the research" detail="This page reflects published job records. Opening the app does not train a model."/><div className="health-summary"><span className="badge">{offline?'Offline':bundle?.status==='ready'?'Published results':'Waiting for verified data'}</span><p>{error||bundle?.reason||'No active error reported in the last bundle.'}</p></div><section className="health-grid"><div><h2>Last completed stages</h2><dl className="health-stages">{['fetch','validation','prediction','publication'].map(stage=><div key={stage}><dt>{stage}</dt><dd>{pkTime(bundle?.stages[stage])}</dd></div>)}</dl></div><div><h2>Model & calendar</h2><p>Active model: {bundle?.model_versions.join(', ')||'No trained model'}</p><p>Calendar coverage through: {pkTime(bundle?.calendar_coverage_until)}</p><p>Source session coverage: {bundle?.source_session_coverage||'Not verified'}</p></div></section><h2>Source availability</h2><div className="sources">{bundle?.sources.map((s,i)=><article key={i}><div><h3>{String(s.name)}</h3><span className="source-status">{String(s.status).replaceAll('_',' ')}</span></div><p>{String(s.reason)}</p><a href={safeURL(s.url)} target="_blank" rel="noreferrer">Source documentation ↗</a></article>)}</div></>;
}
export function App(){
 const [page,setPage]=useState<Page>('Overview');const [horizon,setHorizon]=useState(1);
 const [data,setData]=useState<Loaded|null>(null);const [error,setError]=useState<string|null>(null);
 const [loading,setLoading]=useState(true);const [now,setNow]=useState(Date.now());const [offline,setOffline]=useState(!navigator.onLine);
 const refresh=useCallback(async()=>{setLoading(true);try{const result=await loadBundle();setData(result);setError(result.error);setOffline(result.offline);}catch(e){setError(e instanceof Error?e.message:'Unable to check publication');}finally{setLoading(false);setNow(Date.now());}},[]);
 useEffect(()=>{void refresh();const timer=window.setInterval(()=>{setNow(Date.now());if(document.visibilityState==='visible')void refresh();},60000);const connection=()=>{setOffline(!navigator.onLine);setNow(Date.now());};const visible=()=>{setNow(Date.now());if(document.visibilityState==='visible')void refresh();};window.addEventListener('online',connection);window.addEventListener('offline',connection);document.addEventListener('visibilitychange',visible);return()=>{clearInterval(timer);window.removeEventListener('online',connection);window.removeEventListener('offline',connection);document.removeEventListener('visibilitychange',visible);};},[refresh]);
 const bundle=data?.bundle||null;
 return <div className="app-shell"><a className="skip-link" href="#main">Skip to content</a><header className="masthead"><a className="wordmark" href="./" aria-label="KSE-100 Research desk home">KSE<span>/</span>100<small>Research desk</small></a><div className="masthead-right"><span className="research-tag">Personal research</span><button onClick={()=>void refresh()} disabled={loading} className="refresh" aria-label="Refresh published results"><span aria-hidden="true">↻</span><span>{loading?'Checking...':'Refresh'}</span></button></div></header><div className="status-line" role="status" aria-live="polite">{offline?'Offline · showing the last verified publication':loading?'Checking published results':error?'Publication check failed · '+error:bundle?.status==='ready'?'Published research · check target and update deadlines':'Awaiting verified sources · no probabilities published'}</div><div className="workspace"><nav aria-label="Main navigation">{pages.map((name,i)=><button key={name} aria-current={page===name?'page':undefined} onClick={()=>setPage(name)}><span aria-hidden="true">{glyphs[i]}</span>{name}</button>)}<div className="sidebar-note"><span className="status-dot"/><p>Evidence first.<br/>Every session.</p></div></nav><main id="main">{(page==="Watchlist"||page==="Evidence")&&<div className="global-horizon"><Horizon value={horizon} set={setHorizon}/></div>}{page==='Overview'?<Overview bundle={bundle} horizon={horizon} setHorizon={setHorizon} now={now}/>:page==='Watchlist'?<Watchlist bundle={bundle} horizon={horizon} now={now}/>:page==='Evidence'?<Evidence bundle={bundle} horizon={horizon}/>:page==='Drivers'?<Drivers bundle={bundle}/>:<Health bundle={bundle} offline={offline} error={error}/>}</main></div><footer><p>KSE-100 Research Desk <span>·</span> Research estimates, not trade execution.</p><details><summary>Install on Android & use offline</summary><p>Open this site over HTTPS in Chrome on Android. Use the browser menu → Add to Home screen → Install. After one online visit, the app shell and last verified bundle remain available offline. Expired results are labelled as history. A physical Android installation has not yet been verified.</p></details></footer></div>;
}
