/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Attribution = string[];
export type CalendarCoverageUntil = string | null;
export type Drivers = {
  [k: string]: unknown;
}[];
export type Cutoff = string;
export type ExpiresAt = string;
export type FeatureVersion = string;
export type Fixture = boolean;
export type Horizon = 1 | 5;
export type Instrument = string;
export type InstrumentName = string | null;
export type IssuedAt = string;
export type ModelVersion = string | null;
export type NextOpenAt = string;
export type PNotUp = number | null;
export type PUp = number | null;
export type Policy = string;
export type ReferenceClose = number | null;
export type ReferenceSession = string;
export type ReturnBasis = string;
export type SchemaVersion = "1";
export type Scorecard = string | null;
export type Sector = string | null;
export type Signal = "up" | "not_up" | "no_strong_signal" | "unavailable";
export type Snapshot = string;
export type SuppressionReason = string | null;
export type Symbol = string | null;
export type TargetDefinition = string;
export type TargetSession = string;
export type UpdateDueAt = string;
export type ValidationStatus = "research" | "validated" | "unavailable";
export type Forecasts = Forecast[];
export type GeneratedAt = string;
export type History = Forecast[];
export type Metrics = {
  [k: string]: unknown;
}[];
export type Mode = "production" | "fixture";
export type ModelVersions = string[];
export type CorrectionOf = string | null;
export type Direction = "up" | "down" | "unchanged";
export type ForecastKey = string;
export type Label = 0 | 1;
export type RealizedReturn = number;
export type RecordedAt = string;
export type TargetClose = number;
export type TargetSession1 = string;
export type Vintage = string;
export type Outcomes = Outcome[];
export type Reason = string | null;
export type SchemaVersion1 = "1";
export type SourceSessionCoverage = string | null;
export type Sources = {
  [k: string]: unknown;
}[];
export type Status = "ready" | "blocked" | "failed";
export type UpdateDueAt1 = string | null;

export interface Bundle {
  attribution: Attribution;
  calendar_coverage_until: CalendarCoverageUntil;
  drivers: Drivers;
  forecasts: Forecasts;
  generated_at: GeneratedAt;
  history: History;
  metrics: Metrics;
  mode: Mode;
  model_versions: ModelVersions;
  outcomes: Outcomes;
  reason: Reason;
  schema_version?: SchemaVersion1;
  source_session_coverage: SourceSessionCoverage;
  sources: Sources;
  stages: Stages;
  status: Status;
  update_due_at: UpdateDueAt1;
}
export interface Forecast {
  cutoff: Cutoff;
  expires_at: ExpiresAt;
  feature_version: FeatureVersion;
  fixture?: Fixture;
  horizon: Horizon;
  instrument: Instrument;
  instrument_name?: InstrumentName;
  issued_at: IssuedAt;
  model_version: ModelVersion;
  next_open_at: NextOpenAt;
  p_not_up: PNotUp;
  p_up: PUp;
  policy: Policy;
  reference_close: ReferenceClose;
  reference_session: ReferenceSession;
  return_basis: ReturnBasis;
  schema_version?: SchemaVersion;
  scorecard: Scorecard;
  sector?: Sector;
  signal: Signal;
  snapshot: Snapshot;
  suppression_reason: SuppressionReason;
  symbol?: Symbol;
  target_definition: TargetDefinition;
  target_session: TargetSession;
  update_due_at: UpdateDueAt;
  validation_status: ValidationStatus;
}
export interface Outcome {
  correction_of?: CorrectionOf;
  direction: Direction;
  forecast_key: ForecastKey;
  label: Label;
  realized_return: RealizedReturn;
  recorded_at: RecordedAt;
  target_close: TargetClose;
  target_session: TargetSession1;
  vintage: Vintage;
}
export interface Stages {
  [k: string]: string | null;
}
